### ISSUE TITLE
root.$pdf.pages[i].items is null

### ISSUE THREAD

**Issue by SamDuvall** [jsreport/jsreport-pdf-utils#29]
I'm getting an error where `items` is `null` in rendering the table of contents using the "TOC - table of contents" code for `getPage` here: https://jsreport.net/learn/pdf-utils. This only became an issue when upgrading from 1.8.0 to 1.9.0 and the issue does not seem to be resolved in 1.10.1 either. I looked that the change history, but I cannot figure out what caused the issue. The issue is also random. On successive renderings, different pages will have `items` as `null`. Any ideas?

**Comment by SamDuvall** [comment]
I also get the following error when the PDF renders properly on 1.8.0

```
pdf utils failed to remove the hidden marks from pdf, this has no significant impact, but please report the issue. Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
    at processChunkSync (zlib.js:431:12)
    at zlibBufferSync (zlib.js:168:12)
    at Object.syncBufferWrapper [as unzipSync] (zlib.js:766:14)
    at processStream (.../node_modules/jsreport-pdf-utils/lib/utils/processText.js:50:22)
    at processStream (.../node_modules/jsreport-pdf-utils/lib/utils/processText.js:74:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (.../node_modules/jsreport-pdf-utils/lib/utils/processText.js:200:7)
    at async Object.postprocess (.../node_modules/jsreport-pdf-utils/lib/utils/pdfManipulator.js:91:7)
    at async module.exports (.../node_modules/jsreport-pdf-utils/lib/scriptPdfProcessing.js:82:5) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

**Comment by pofider** [comment]
Would you be able to upload a minimal export.zip with jsreport entities replicating the error?

**Comment by SamDuvall** [comment]
I would be happy to help replicate the error, but I'm not using the JSReport studio. I'm feeding JSReport React-generated HTML/CSS.

**Comment by bigfuture-test** [comment]
I am also facing this issue. This is my example: [Playground](https://playground.jsreport.net/w/bjrmatos/CfJeHyah)

**Comment by pofider** [comment]
@sushil-bigfuture The playground workspace you shared seems to be working. Is this the right one?
