### ISSUE TITLE
Error rendering merge template with headers

### ISSUE THREAD

**Issue by trekuartista** [jsreport/jsreport-pdf-utils#6]
I'm trying to make a pdf with a merge template, rendering on every peage, but in the main template when add a header to show page numbers, it doesn't work, show an error: 
Invalid PDF structure
Error
    at InvalidPDFExceptionClosure (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:461:35)
    at Object.<anonymous> (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:464:2)
    at __w_pdfjs_require__ (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:52:30)
    at Object._typeof (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:3009:23)
    at __w_pdfjs_require__ (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:52:30)
    at Object.defineProperty.value (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:95:18)
    at D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:98:10
    at webpackUniversalModuleDefinition (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:25:20)
    at Object.<anonymous> (D:\devel\JsReport2\node_modules\pdfjs-dist\build\pdf.js:32:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

using phantom pdf with jsreport 2.0.0

**Comment by trekuartista** [comment]
I notice, in the merge pdf, adding the next lines:

`{{$pdf.pageNumber}} / {{$pdf.pages.length}}`
will show the page numbers.
